#!/bin/bash
# Setup script for Confluence API environment variables

echo "Confluence API Setup"
echo "==================="
echo ""
echo "This script will help you set up the required environment variables."
echo "It will create a .env file for use with the Python scripts."
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  Warning: .env file already exists!"
    echo -n "Do you want to overwrite it? (y/N): "
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 1
    fi
    echo ""
fi

# Get Confluence domain
echo "Enter your Confluence domain (e.g., yoursite.atlassian.net):"
read -r CONFLUENCE_DOMAIN

# Get email
echo ""
echo "Enter your email address:"
read -r CONFLUENCE_EMAIL

# Get API token
echo ""
echo "Enter your API token (get one from https://id.atlassian.com/manage-profile/security/api-tokens):"
read -s CONFLUENCE_API_TOKEN
echo ""

# Get space ID
echo ""
echo "Enter a Space ID to test with (numeric ID like 123456):"
echo "(You can run 'python3 scripts/test_connection.py' later to find available space IDs)"
read -r CONFLUENCE_SPACE_ID

# Get optional space key
echo ""
echo "Enter a Space Key (optional, e.g., DEMO, TEST):"
read -r CONFLUENCE_SPACE_KEY

# Create .env file
cat > .env << EOF
# Confluence API Configuration
# Generated by setup_env.sh on $(date)

# Your Confluence domain
CONFLUENCE_DOMAIN=$CONFLUENCE_DOMAIN

# Your email address
CONFLUENCE_EMAIL=$CONFLUENCE_EMAIL

# Your API token from https://id.atlassian.com/manage-profile/security/api-tokens
CONFLUENCE_API_TOKEN=$CONFLUENCE_API_TOKEN

# A numeric Space ID to use for testing
CONFLUENCE_SPACE_ID=$CONFLUENCE_SPACE_ID

# Optional: Space key
CONFLUENCE_SPACE_KEY=$CONFLUENCE_SPACE_KEY
EOF

echo ""
echo "✅ Configuration saved to .env file!"
echo ""
echo "Summary:"
echo "--------"
echo "CONFLUENCE_DOMAIN=$CONFLUENCE_DOMAIN"
echo "CONFLUENCE_EMAIL=$CONFLUENCE_EMAIL"
echo "CONFLUENCE_API_TOKEN=<hidden>"
echo "CONFLUENCE_SPACE_ID=$CONFLUENCE_SPACE_ID"
echo "CONFLUENCE_SPACE_KEY=$CONFLUENCE_SPACE_KEY"
echo ""
echo "The .env file has been created. The Python scripts will automatically load"
echo "these values when you run them."
echo ""
echo "Next steps:"
echo "1. Test your connection: python3 scripts/test_connection.py"
echo "2. Create a test page:   python3 scripts/test_formatting.py"
echo ""
echo "Note: Keep your .env file secure and never commit it to version control!"